version: '3.8'
services:
  my_python_app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: my_python_app_container
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    command: python app.py
  angular-app:
    build: 
      context: ./
      dockerfile: docker/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/frontend/src