version: '3.8'
services:
  python-app:
    build: 
      context: ./
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./server:/var/www/html
    ports:
      - 5000:5000
  angular-app:
    build: 
      context: ./
      dockerfile: docker/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/frontend/src